In [8]:
import requests

In [9]:
import pandas as pd
events = pd.read_parquet('../../data/events.parquet')

In [10]:
events

     user_id    item_id  track_seq started_at  rank
0          0      99262          1 2022-07-17    10
1          0     589498          2 2022-07-19     9
6          0     597196          7 2022-07-25     8
7          0     597199          8 2022-07-25     7
14         0   10327926         15 2022-08-19     6
..       ...        ...        ...        ...   ...
283  1374582   94960284        284 2022-12-29     5
288  1374582   97220301        289 2022-12-29     4
289  1374582   97241171        290 2022-12-29     3
290  1374582   98542641        291 2022-12-29     2
291  1374582  100736375        292 2022-12-30     1

[13023329 rows x 5 columns]

In [5]:
final_recommendations = pd.read_parquet('../../data/final_recommendations.parquet').sample(10)

In [19]:
final_recommendations.set_index('user_id').index.unique()

Index([ 493820, 1245731,  294280,  974780,  622601,  847759, 1229383,  708611,
        644679,  372353],
      dtype='int32', name='user_id')

In [12]:
events[~events['user_id'].isin(final_recommendations['user_id'].unique())]

     user_id    item_id  track_seq started_at  rank
0          0      99262          1 2022-07-17    10
1          0     589498          2 2022-07-19     9
6          0     597196          7 2022-07-25     8
7          0     597199          8 2022-07-25     7
14         0   10327926         15 2022-08-19     6
..       ...        ...        ...        ...   ...
283  1374582   94960284        284 2022-12-29     5
288  1374582   97220301        289 2022-12-29     4
289  1374582   97241171        290 2022-12-29     3
290  1374582   98542641        291 2022-12-29     2
291  1374582  100736375        292 2022-12-30     1

[13023229 rows x 5 columns]

In [ ]:
items[items['user_id']]

### recs_service

In [11]:
# recommendations_online

recommendations_url = 'http://127.0.0.1:8000'

headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
params = {'user_id': 1337055}

resp = requests.get(f'{recommendations_url}/recommendations_online', headers=headers, params=params)

if resp.status_code == 200:
    recs = resp.json()
else:
    recs = []
    print(f'status code: {resp.status_code}')
    
print(recs)

{'recs': []}

In [12]:
# recommendations_offline

recommendations_url = 'http://127.0.0.1:8000'

headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
params = {'user_id': 1337055}

resp = requests.get(f'{recommendations_url}/recommendations_offline', headers=headers, params=params)

if resp.status_code == 200:
    recs = resp.json()
else:
    recs = []
    print(f'status code: {resp.status_code}')
    
print(recs)

{'recs': [93126179, 81848875, 83063895, 65851540, 84382282, 78426489, 93390818, 51516485, 32947997, 33311009, 56204557, 60292250, 76434671, 73376988, 85660864, 45499814, 51241318, 49961817, 75642961, 57921154, 84382287, 54798445, 94696082, 39257277, 75944934, 61565558, 44184116, 82783144, 62352387, 34976783, 70619465, 50821247, 35505245, 66869588, 56920241, 54400255, 54837415, 50834580, 95089997, 44279380, 29569939, 88476064, 49125069, 86710605, 58515506, 72055319, 68562711, 29611476, 89305091, 86081547, 50685843, 57799893, 52380688, 78194999, 48591706, 56776952, 30049955, 43052381, 71308883, 63591534, 42197229, 66322065, 47627256, 93707221, 29544272, 78824202, 56920237, 79071657, 64496155, 93556487, 39089632, 60725745, 88900923, 80153541, 2758009, 98901753, 17902234, 62244864, 43526313, 95728483, 44625560, 51422266, 10776533, 50684233, 54945765, 85192958, 89047687, 33977439, 53357546, 41249159, 44858413, 82036283, 43942453, 69459326, 68348389, 68938482, 45130892, 32182642, 31078723, 6705392]}

In [13]:
# recommendations

recommendations_url = 'http://127.0.0.1:8000'

headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
params = {'user_id': 1337055}

resp = requests.get(f'{recommendations_url}/recommendations', headers=headers, params=params)

if resp.status_code == 200:
    recs = resp.json()
else:
    recs = []
    print(f'status code: {resp.status_code}')
    
print(recs)

{'recs': [93126179, 81848875, 83063895, 65851540, 84382282, 78426489, 93390818, 51516485, 32947997, 33311009, 56204557, 60292250, 76434671, 73376988, 85660864, 45499814, 51241318, 49961817, 75642961, 57921154, 84382287, 54798445, 94696082, 39257277, 75944934, 61565558, 44184116, 82783144, 62352387, 34976783, 70619465, 50821247, 35505245, 66869588, 56920241, 54400255, 54837415, 50834580, 95089997, 44279380, 29569939, 88476064, 49125069, 86710605, 58515506, 72055319, 68562711, 29611476, 89305091, 86081547, 50685843, 57799893, 52380688, 78194999, 48591706, 56776952, 30049955, 43052381, 71308883, 63591534, 42197229, 66322065, 47627256, 93707221, 29544272, 78824202, 56920237, 79071657, 64496155, 93556487, 39089632, 60725745, 88900923, 80153541, 2758009, 98901753, 17902234, 62244864, 43526313, 95728483, 44625560, 51422266, 10776533, 50684233, 54945765, 85192958, 89047687, 33977439, 53357546, 41249159, 44858413, 82036283, 43942453, 69459326, 68348389, 68938482, 45130892, 32182642, 31078723, 6705392]}

### events_service

In [17]:
events_store_url = 'http://127.0.0.1:8020'

headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
params = {'user_id': 1337055, 'k': 100}

resp = requests.get(f'{events_store_url}/events', headers=headers, params=params)
if resp.status_code == 200:
    result = resp.json()
else:
    result = None
    print(f'status code: {resp.status_code}')
    
result

{'events': [88159074, 46781719, 24144596, 57123340, 66786934]}

### features_service

In [34]:
import requests

features_store_url = 'http://127.0.0.1:8010'

headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}
params = {'item_id': 99262, 'k': 3}

resp = requests.get(f'{features_store_url}/similar_items', headers=headers, params=params)
if resp.status_code == 200:
    similar_items = resp.json()
else:
    similar_items = None
    print(f'status code: {resp.status_code}')
    
similar_items

{'item_id_2': [855241, 812255, 646679],
 'score': [0.9873615503311157, 0.9867034554481506, 0.9852792024612427]}